version: "3.3"
services:
  web:
    container_name: php-new
    build:
      args:
        user: appuser
        uid: 1000
      context: ./php-fpm
      dockerfile: Dockerfile
    ports:
      - "9000"
    volumes:
      - ../source-bot:/var/www/botlabvn:rw
    logging:
      driver: fluentd  
      options:
        fluentd-address: localhost:24224
        tag: php.logs
    depends_on:  
      - "fluentd" 

  nginx:
    container_name: nginx-new
    build:
      context: ./dockernginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../source-bot:/var/www/botlabvn:rw
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    logging:
      driver: fluentd  
      options:
        fluentd-address: localhost:24224
        tag: nginx.logs
    depends_on:  
      - "fluentd" 

  mysql:
    container_name: db-new
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --log-bin-trust-function-creators=1 --character-set-server=utf8mb4  --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    env_file: .env
    logging:
      driver: fluentd  
      options:
        fluentd-address: localhost:24224
        tag: mysql.logs
    depends_on:  
      - "fluentd" 

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"
    # volumes:
    #   - ./elasticsearch/config:/usr/share/elasticsearch/config

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"